-- AlterTable
ALTER TABLE "benefita"."tabperusahaan" ADD COLUMN     "BATAS_EMAS" INTEGER,
ADD COLUMN     "BATAS_HIJAU" INTEGER,
ADD COLUMN     "CABANG_SITE" VARCHAR(255),
ADD COLUMN     "ID_SIMPEL" VARCHAR(50),
ADD COLUMN     "LINE_BISNIS_SUB" VARCHAR(255),
ADD COLUMN     "PESAING" VARCHAR(255),
ADD COLUMN     "PROSEDUR_PELATIHAN" VARCHAR(255);
